#!/bin/bash
# This script is used to generate test database for the job scheduler on CMS detector at the LHC at CERN.
curl -X PUT http://$HOST_ADDRESS/cern_cms_sheduller2

curl -X PUT http://$HOST_ADDRESS/cern_cms_sheduller2/_design/deadline_time_blocks -d @views/deadline_time_blocks.json
curl -X PUT http://$HOST_ADDRESS/cern_cms_sheduller2/_design/priority_time_blocks -d @views/priority_time_blocks.json
curl -X PUT http://$HOST_ADDRESS/cern_cms_sheduller2/_design/planed_time_blocks -d @views/planed_time_blocks.json

curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Rolf Heuer", "eventsCount": "100", "timePartCount": "days=0, hours=5, minutes=45", "deadline": "2014-01-11 00:00:00", "priority": "1", "groups": "[group2]", "keyWords": "Hadron"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Jean-Roch Vlimant", "eventsCount": "100", "timePartCount": "days=1, hours=1, minutes=30", "deadline": "2014-01-11 00:00:00", "priority": "6", "groups": "[group2]", "keyWords": "Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Giovanni Franzoni", "eventsCount": "75", "timePartCount": "days=0, hours=5, minutes=45", "deadline": "2014-01-03 00:00:00", "priority": "3", "groups": "[group1]", "keyWords": "Bosons, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Jean-Roch Vlimant", "eventsCount": "100", "timePartCount": "days=0, hours=3, minutes=30", "deadline": "2014-01-07 00:00:00", "priority": "3", "groups": "[group1]", "keyWords": "Hadron"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Rolf Heuer", "eventsCount": "50", "timePartCount": "days=1, hours=1, minutes=30", "deadline": "2014-01-11 00:00:00", "priority": "7", "groups": "[group1]", "keyWords": "Bosons, Hadron, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Giovanni Franzoni", "eventsCount": "100", "timePartCount": "days=0, hours=5, minutes=45", "deadline": "2014-01-03 00:00:00", "priority": "6", "groups": "[group1, group2]", "keyWords": "Bosons"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Rolf Heuer", "eventsCount": "125", "timePartCount": "days=0, hours=3, minutes=30", "deadline": "2014-01-03 00:00:00", "priority": "5", "groups": "[group2]", "keyWords": "Bosons, Hadron"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Giovanni Franzoni", "eventsCount": "100", "timePartCount": "days=1, hours=1, minutes=30", "deadline": "2014-01-03 00:00:00", "priority": "3", "groups": "[group1]", "keyWords": "Bosons, Hadron, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Rolf Heuer", "eventsCount": "75", "timePartCount": "days=0, hours=5, minutes=45", "deadline": "2014-01-07 00:00:00", "priority": "9", "groups": "[group1, group2]", "keyWords": "Bosons, Hadron, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Jean-Roch Vlimant", "eventsCount": "125", "timePartCount": "days=0, hours=5, minutes=45", "deadline": "2014-01-11 00:00:00", "priority": "1", "groups": "[group2]", "keyWords": "Hadron, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Rolf Heuer", "eventsCount": "50", "timePartCount": "days=1, hours=1, minutes=30", "deadline": "2014-01-07 00:00:00", "priority": "0", "groups": "[group1, group2]", "keyWords": "Hadron"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Jean-Roch Vlimant", "eventsCount": "125", "timePartCount": "days=1, hours=1, minutes=30", "deadline": "2014-01-11 00:00:00", "priority": "0", "groups": "[group1]", "keyWords": "Bosons"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Jean-Roch Vlimant", "eventsCount": "50", "timePartCount": "days=0, hours=5, minutes=45", "deadline": "2014-01-11 00:00:00", "priority": "7", "groups": "[group2]", "keyWords": "Bosons"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Jean-Roch Vlimant", "eventsCount": "75", "timePartCount": "days=0, hours=5, minutes=45", "deadline": "2014-01-07 00:00:00", "priority": "8", "groups": "[group1, group2]", "keyWords": "Hadron, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Jean-Roch Vlimant", "eventsCount": "75", "timePartCount": "days=0, hours=3, minutes=30", "deadline": "2014-01-07 00:00:00", "priority": "6", "groups": "[group1]", "keyWords": "Hadron, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Jean-Roch Vlimant", "eventsCount": "100", "timePartCount": "days=1, hours=1, minutes=30", "deadline": "2014-01-03 00:00:00", "priority": "4", "groups": "[group1, group2]", "keyWords": "Hadron, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Rolf Heuer", "eventsCount": "100", "timePartCount": "days=0, hours=3, minutes=30", "deadline": "2014-01-11 00:00:00", "priority": "0", "groups": "[group1]", "keyWords": "Bosons, Hadron"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Jean-Roch Vlimant", "eventsCount": "75", "timePartCount": "days=0, hours=3, minutes=30", "deadline": "2014-01-03 00:00:00", "priority": "2", "groups": "[group1, group2]", "keyWords": "Bosons, Hadron"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Jean-Roch Vlimant", "eventsCount": "150", "timePartCount": "days=1, hours=1, minutes=30", "deadline": "2014-01-11 00:00:00", "priority": "3", "groups": "[group2]", "keyWords": "Bosons, Hadron"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Giovanni Franzoni", "eventsCount": "75", "timePartCount": "days=0, hours=5, minutes=45", "deadline": "2014-01-11 00:00:00", "priority": "8", "groups": "[group2]", "keyWords": "Bosons"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Giovanni Franzoni", "eventsCount": "100", "timePartCount": "days=0, hours=3, minutes=30", "deadline": "2014-01-11 00:00:00", "priority": "4", "groups": "[group1, group2]", "keyWords": "Bosons, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Rolf Heuer", "eventsCount": "75", "timePartCount": "days=0, hours=3, minutes=30", "deadline": "2014-01-07 00:00:00", "priority": "3", "groups": "[group1, group2]", "keyWords": "Hadron, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Jean-Roch Vlimant", "eventsCount": "125", "timePartCount": "days=0, hours=3, minutes=30", "deadline": "2014-01-03 00:00:00", "priority": "2", "groups": "[group1, group2]", "keyWords": "Bosons, Hadron"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Rolf Heuer", "eventsCount": "150", "timePartCount": "days=1, hours=1, minutes=30", "deadline": "2014-01-03 00:00:00", "priority": "9", "groups": "[group2]", "keyWords": "Bosons, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Rolf Heuer", "eventsCount": "50", "timePartCount": "days=0, hours=5, minutes=45", "deadline": "2014-01-11 00:00:00", "priority": "7", "groups": "[group2]", "keyWords": "Bosons"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Jean-Roch Vlimant", "eventsCount": "125", "timePartCount": "days=0, hours=3, minutes=30", "deadline": "2014-01-07 00:00:00", "priority": "9", "groups": "[group2]", "keyWords": "Bosons, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Rolf Heuer", "eventsCount": "150", "timePartCount": "days=0, hours=3, minutes=30", "deadline": "2014-01-03 00:00:00", "priority": "9", "groups": "[group1, group2]", "keyWords": "Bosons"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Rolf Heuer", "eventsCount": "125", "timePartCount": "days=0, hours=5, minutes=45", "deadline": "2014-01-07 00:00:00", "priority": "9", "groups": "[group1, group2]", "keyWords": "Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Jean-Roch Vlimant", "eventsCount": "100", "timePartCount": "days=0, hours=5, minutes=45", "deadline": "2014-01-11 00:00:00", "priority": "5", "groups": "[group1, group2]", "keyWords": "Bosons, Hadron, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Jean-Roch Vlimant", "eventsCount": "50", "timePartCount": "days=1, hours=1, minutes=30", "deadline": "2014-01-11 00:00:00", "priority": "0", "groups": "[group2]", "keyWords": "Bosons, Hadron, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Rolf Heuer", "eventsCount": "125", "timePartCount": "days=0, hours=3, minutes=30", "deadline": "2014-01-07 00:00:00", "priority": "0", "groups": "[group1, group2]", "keyWords": "Hadron, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Giovanni Franzoni", "eventsCount": "125", "timePartCount": "days=0, hours=3, minutes=30", "deadline": "2014-01-03 00:00:00", "priority": "4", "groups": "[group2]", "keyWords": "Bosons"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Rolf Heuer", "eventsCount": "50", "timePartCount": "days=0, hours=3, minutes=30", "deadline": "2014-01-03 00:00:00", "priority": "9", "groups": "[group1, group2]", "keyWords": "Bosons, Hadron, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Rolf Heuer", "eventsCount": "150", "timePartCount": "days=1, hours=1, minutes=30", "deadline": "2014-01-07 00:00:00", "priority": "0", "groups": "[group1]", "keyWords": "Bosons"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Giovanni Franzoni", "eventsCount": "100", "timePartCount": "days=1, hours=1, minutes=30", "deadline": "2014-01-07 00:00:00", "priority": "0", "groups": "[group1, group2]", "keyWords": "Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Rolf Heuer", "eventsCount": "50", "timePartCount": "days=0, hours=5, minutes=45", "deadline": "2014-01-03 00:00:00", "priority": "7", "groups": "[group1, group2]", "keyWords": "Bosons, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Rolf Heuer", "eventsCount": "50", "timePartCount": "days=0, hours=3, minutes=30", "deadline": "2014-01-07 00:00:00", "priority": "7", "groups": "[group1, group2]", "keyWords": "Hadron, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Rolf Heuer", "eventsCount": "150", "timePartCount": "days=0, hours=3, minutes=30", "deadline": "2014-01-03 00:00:00", "priority": "5", "groups": "[group1, group2]", "keyWords": "Bosons, Hadron"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Rolf Heuer", "eventsCount": "75", "timePartCount": "days=0, hours=5, minutes=45", "deadline": "2014-01-11 00:00:00", "priority": "0", "groups": "[group1]", "keyWords": "Bosons"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "deadlineBlock", "autor": "Rolf Heuer", "eventsCount": "50", "timePartCount": "days=1, hours=1, minutes=30", "deadline": "2014-01-11 00:00:00", "priority": "1", "groups": "[group1]", "keyWords": "Hadron, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Rolf Heuer", "eventsCount": "125", "timePartCount": "days=0, hours=3, minutes=30", "priority": "0", "groups": "[group2]", "keyWords": "Bosons"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Giovanni Franzoni", "eventsCount": "100", "timePartCount": "days=0, hours=5, minutes=45", "priority": "9", "groups": "[group1]", "keyWords": "Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Giovanni Franzoni", "eventsCount": "100", "timePartCount": "days=1, hours=1, minutes=30", "priority": "5", "groups": "[group1, group2]", "keyWords": "Hadron"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Jean-Roch Vlimant", "eventsCount": "125", "timePartCount": "days=0, hours=3, minutes=30", "priority": "6", "groups": "[group1, group2]", "keyWords": "Bosons, Hadron"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Giovanni Franzoni", "eventsCount": "100", "timePartCount": "days=0, hours=5, minutes=45", "priority": "1", "groups": "[group1]", "keyWords": "Bosons"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Jean-Roch Vlimant", "eventsCount": "150", "timePartCount": "days=0, hours=5, minutes=45", "priority": "8", "groups": "[group2]", "keyWords": "Bosons, Hadron, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Jean-Roch Vlimant", "eventsCount": "150", "timePartCount": "days=0, hours=5, minutes=45", "priority": "6", "groups": "[group2]", "keyWords": "Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Giovanni Franzoni", "eventsCount": "125", "timePartCount": "days=0, hours=5, minutes=45", "priority": "6", "groups": "[group1]", "keyWords": "Bosons"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Rolf Heuer", "eventsCount": "75", "timePartCount": "days=1, hours=1, minutes=30", "priority": "4", "groups": "[group2]", "keyWords": "Bosons, Hadron, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Giovanni Franzoni", "eventsCount": "100", "timePartCount": "days=1, hours=1, minutes=30", "priority": "3", "groups": "[group1, group2]", "keyWords": "Bosons, Hadron"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Giovanni Franzoni", "eventsCount": "125", "timePartCount": "days=0, hours=3, minutes=30", "priority": "3", "groups": "[group2]", "keyWords": "Hadron"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Rolf Heuer", "eventsCount": "150", "timePartCount": "days=0, hours=5, minutes=45", "priority": "6", "groups": "[group2]", "keyWords": "Bosons, Hadron"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Rolf Heuer", "eventsCount": "150", "timePartCount": "days=0, hours=3, minutes=30", "priority": "0", "groups": "[group1, group2]", "keyWords": "Bosons, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Rolf Heuer", "eventsCount": "50", "timePartCount": "days=0, hours=3, minutes=30", "priority": "7", "groups": "[group2]", "keyWords": "Bosons, Hadron"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Rolf Heuer", "eventsCount": "125", "timePartCount": "days=0, hours=5, minutes=45", "priority": "6", "groups": "[group1, group2]", "keyWords": "Hadron, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Giovanni Franzoni", "eventsCount": "100", "timePartCount": "days=0, hours=5, minutes=45", "priority": "5", "groups": "[group1]", "keyWords": "Bosons, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Jean-Roch Vlimant", "eventsCount": "150", "timePartCount": "days=0, hours=5, minutes=45", "priority": "1", "groups": "[group2]", "keyWords": "Bosons, Hadron, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Rolf Heuer", "eventsCount": "125", "timePartCount": "days=1, hours=1, minutes=30", "priority": "4", "groups": "[group1, group2]", "keyWords": "Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Jean-Roch Vlimant", "eventsCount": "50", "timePartCount": "days=1, hours=1, minutes=30", "priority": "8", "groups": "[group2]", "keyWords": "Bosons, Hadron, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Jean-Roch Vlimant", "eventsCount": "125", "timePartCount": "days=0, hours=5, minutes=45", "priority": "4", "groups": "[group1, group2]", "keyWords": "Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Giovanni Franzoni", "eventsCount": "100", "timePartCount": "days=0, hours=3, minutes=30", "priority": "4", "groups": "[group1, group2]", "keyWords": "Bosons, Hadron"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Giovanni Franzoni", "eventsCount": "100", "timePartCount": "days=1, hours=1, minutes=30", "priority": "5", "groups": "[group1, group2]", "keyWords": "Bosons, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Jean-Roch Vlimant", "eventsCount": "150", "timePartCount": "days=1, hours=1, minutes=30", "priority": "1", "groups": "[group1, group2]", "keyWords": "Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Rolf Heuer", "eventsCount": "75", "timePartCount": "days=1, hours=1, minutes=30", "priority": "6", "groups": "[group1, group2]", "keyWords": "Bosons, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Giovanni Franzoni", "eventsCount": "150", "timePartCount": "days=1, hours=1, minutes=30", "priority": "6", "groups": "[group2]", "keyWords": "Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Giovanni Franzoni", "eventsCount": "75", "timePartCount": "days=1, hours=1, minutes=30", "priority": "9", "groups": "[group2]", "keyWords": "Bosons"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Giovanni Franzoni", "eventsCount": "150", "timePartCount": "days=1, hours=1, minutes=30", "priority": "3", "groups": "[group1]", "keyWords": "Bosons, Hadron"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Jean-Roch Vlimant", "eventsCount": "50", "timePartCount": "days=1, hours=1, minutes=30", "priority": "1", "groups": "[group1]", "keyWords": "Bosons, Hadron"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Giovanni Franzoni", "eventsCount": "125", "timePartCount": "days=0, hours=3, minutes=30", "priority": "0", "groups": "[group2]", "keyWords": "Bosons"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Giovanni Franzoni", "eventsCount": "100", "timePartCount": "days=1, hours=1, minutes=30", "priority": "6", "groups": "[group2]", "keyWords": "Bosons, Hadron"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Giovanni Franzoni", "eventsCount": "50", "timePartCount": "days=1, hours=1, minutes=30", "priority": "3", "groups": "[group1, group2]", "keyWords": "Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Giovanni Franzoni", "eventsCount": "50", "timePartCount": "days=1, hours=1, minutes=30", "priority": "5", "groups": "[group2]", "keyWords": "Hadron, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Rolf Heuer", "eventsCount": "75", "timePartCount": "days=0, hours=5, minutes=45", "priority": "2", "groups": "[group1, group2]", "keyWords": "Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Giovanni Franzoni", "eventsCount": "50", "timePartCount": "days=1, hours=1, minutes=30", "priority": "9", "groups": "[group1, group2]", "keyWords": "Hadron"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Rolf Heuer", "eventsCount": "150", "timePartCount": "days=0, hours=3, minutes=30", "priority": "4", "groups": "[group2]", "keyWords": "Bosons, Hadron, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Rolf Heuer", "eventsCount": "100", "timePartCount": "days=0, hours=3, minutes=30", "priority": "9", "groups": "[group1, group2]", "keyWords": "Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Giovanni Franzoni", "eventsCount": "150", "timePartCount": "days=0, hours=3, minutes=30", "priority": "9", "groups": "[group2]", "keyWords": "Hadron"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Rolf Heuer", "eventsCount": "50", "timePartCount": "days=0, hours=3, minutes=30", "priority": "4", "groups": "[group2]", "keyWords": "Bosons, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Giovanni Franzoni", "eventsCount": "150", "timePartCount": "days=0, hours=5, minutes=45", "priority": "7", "groups": "[group2]", "keyWords": "Bosons, Hadron, Fermions"}' http://$HOST_ADDRESS/cern_cms_sheduller2
curl -X POST -H "Content-Type: application/json" --data '{"type": "priorityBlock", "autor": "Giovanni Franzoni", "eventsCount": "75", "timePartCount": "days=1, hours=1, minutes=30", "priority": "7", "groups": "[group1]", "keyWords": "Bosons, Hadron"}' http://$HOST_ADDRESS/cern_cms_sheduller2
